### PR TITLE
Minor spelling corrections

### PR DESCRIPTION
**Pull request by TheWelcomer**
Hi, I'm sort of learning how to use GitHub so I thought I would make a pull request with some spelling changes to test it out. I hope this is helpful.

### CODE REVIEW

**Comment by Z3R0-cmd** [comment]
image
image
these are technically incorrect

**Review by darklol9 — APPROVED** [review]

**Review by 0t4u — APPROVED** [review]

**Review by Nowilltolife — APPROVED** [review]

**Comment by slowrecall** [comment]
What a meme, just no. 

I appreciate your learning how to interact with such a useful and helpful platform like GH but this is not a suitable PR. 

@darklol9 @0t4u @Nowilltolife - argue with the wall. 

PR closed.

**Comment by Nowilltolife** [comment]
@slowrecall, how can you not see the major performance increase which this PR sprouts. It is clearly deserving of a merge!

**Comment by darklol9** [comment]
Pussio this deserves to be merged

**Comment by slowrecall** [comment]
> Pussio this deserves to be merged

Reported, and banned.

**Comment by slowrecall** [comment]
To stop you all from crying, this thread has been locked.

Merry Christmas and a Happy New Year to you all. :)

**Pull request closed without merging**
