### PR TITLE
Add some more strings

### PR DESCRIPTION
**Pull request by IlluminatiFish**
Adds some more strings to the blacklist

### CODE REVIEW

**Comment by slowrecall** [comment]
> Adds some more strings to the blacklist

As you can tell, the current file has Discord related strings blacklisted only, hence the name "Token Logger Protection Provider".

**Review by slowrecall — CHANGES_REQUESTED** [review]
Looks good to me, however I would not add this in this particular class as they are not for token logging but rather minecraft accounts. 
Suggestion: Expand on this further, and then move the new strings into a class called MinecraftProtectionProvider?

**Comment by IlluminatiFish** [comment]
> 

Ah yes indeed it is only Token Logging related strings my bad, however the only two Minecraft specific strings in my commit are 
```
.feather/accounts.json
essential/microsoft_accounts.json
````
so I believe the other three can stay.

Will add the Minecraft related strings to its own class (`MinecraftProtectionProvider`)

**Comment by slowrecall** [comment]
> Will add the Minecraft

Sounds good!

**Review by slowrecall — APPROVED** [review]
Looks fine!

**Comment by IlluminatiFish** [comment]
> Looks fine!

🤝

**Pull request merged**
